# Generated by Django 2.1.3 on 2020-04-28 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sprav', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polymers',
            old_name='content_diene',
            new_name='diene_content',
        ),
        migrations.RenameField(
            model_name='polymers',
            old_name='content_ethylene',
            new_name='ethylene_content',
        ),
    ]
