# Generated by Django 2.1.3 on 2020-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprav', '0002_auto_20200428_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymers',
            name='diene_content',
            field=models.FloatField(blank=True, null=True, verbose_name='Содержание диена'),
        ),
        migrations.AlterField(
            model_name='polymers',
            name='ethylene_content',
            field=models.FloatField(blank=True, null=True, verbose_name='Содержание этилена'),
        ),
        migrations.AlterField(
            model_name='polymers',
            name='ptr',
            field=models.FloatField(null=True, verbose_name='ПТР'),
        ),
        migrations.AlterField(
            model_name='polymers',
            name='t_vika',
            field=models.IntegerField(null=True, verbose_name='Температура Вика'),
        ),
        migrations.AlterField(
            model_name='polymers',
            name='viscosity_Mooney',
            field=models.FloatField(blank=True, null=True, verbose_name='Вязкость Муни'),
        ),
    ]
