# Generated by Django 2.1.3 on 2020-04-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sprav', '0003_auto_20200428_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polymers',
            name='diene_content',
            field=models.FloatField(blank=True, null=True, verbose_name='Содержание этилиденнорборнена'),
        ),
        migrations.AlterField(
            model_name='polymers',
            name='ptr',
            field=models.FloatField(blank=True, null=True, verbose_name='ПТР'),
        ),
        migrations.AlterField(
            model_name='polymers',
            name='shortcode',
            field=models.CharField(max_length=50, unique=True, verbose_name='Марка'),
        ),
        migrations.AlterField(
            model_name='polymers',
            name='t_vika',
            field=models.IntegerField(blank=True, null=True, verbose_name='Температура Вика'),
        ),
    ]
